// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPBAGTxIfhutN2qiP8qtqzywsF5d7gwcA',
    appId: '1:5843068756:android:3d91d17d9f65cc25e14ac1',
    messagingSenderId: '5843068756',
    projectId: 'audiobook-cae61',
    databaseURL: 'https://audiobook-cae61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'audiobook-cae61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtOt7CfqZ9fjLRTU6XDHFicUt8O9B0Hwo',
    appId: '1:5843068756:ios:8355ab19c893fae6e14ac1',
    messagingSenderId: '5843068756',
    projectId: 'audiobook-cae61',
    databaseURL: 'https://audiobook-cae61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'audiobook-cae61.appspot.com',
    iosBundleId: 'com.example.audioBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtOt7CfqZ9fjLRTU6XDHFicUt8O9B0Hwo',
    appId: '1:5843068756:ios:a3a73d168b744126e14ac1',
    messagingSenderId: '5843068756',
    projectId: 'audiobook-cae61',
    databaseURL: 'https://audiobook-cae61-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'audiobook-cae61.appspot.com',
    iosBundleId: 'com.example.audioBook.RunnerTests',
  );
}
